name: Copy Files from comm10 auto

on:
  schedule:
    - cron: '0 8 * * 1-5' # Uruchamia workflow o 10:00 czasu warszawskiego (UTC+2) w dni robocze

jobs:
  copy-files:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout target repository
      uses: actions/checkout@v3
      with:
        repository: Mike7205/LSTM_Models
        path: target_repo
        token: ${{ secrets.PAT }}

    - name: Checkout source repository
      uses: actions/checkout@v3
      with:
        repository: Mike7205/comm10
        path: source_repo
        token: ${{ secrets.PAT }}

    - name: Copy files
      run: |
        cp source_repo/D1_EUR_a.pkl target_repo/
        cp source_repo/D1_USD_a.pkl target_repo/
        cp source_repo/D5_eur_tabel.pkl target_repo/

    - name: Commit and push changes
      run: |
        cd target_repo
        git config --global user.email "michal.lesniewski108@gmail.com"
        git config --global user.name "Mike7205"
        git add D1_EUR_a.pkl D1_USD_a.pkl D5_eur_tabel.pkl
        git commit -m "Add files from comm10 repository"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}
